# This is a basic workflow to help you get started with Actions

name: NPM Publish

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  release:
    types:
      - "published"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  prerelease:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v1
            - name: Make stable release to npm
              uses: esamatti/npm-release@v2
              with:
                  type: stable
                  token: ${{ secrets.NPM_TOKEN }}
